# Generated by Django 4.2.8 on 2025-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Revenue",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=15)),
                ("tickets_count", models.IntegerField(default=0)),
                ("parcels_count", models.IntegerField(default=0)),
                (
                    "expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("profit", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "verbose_name": "Revenu",
                "verbose_name_plural": "Revenus",
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
    ]
