# Generated by Django 5.2.6 on 2025-09-25 06:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("mobile_money", "Mobile Money"),
                            ("card", "Carte bancaire"),
                            ("crypto", "Cryptomonnaie"),
                            ("bank_transfer", "Virement bancaire"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                        ],
                        max_length=20,
                        verbose_name="Type de méthode",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "supported_currencies",
                    models.JSONField(default=list, verbose_name="Devises supportées"),
                ),
                (
                    "min_deposit",
                    models.JSONField(
                        default=dict, verbose_name="Dépôt minimum par devise"
                    ),
                ),
                (
                    "max_deposit",
                    models.JSONField(
                        default=dict, verbose_name="Dépôt maximum par devise"
                    ),
                ),
                (
                    "min_withdrawal",
                    models.JSONField(
                        default=dict, verbose_name="Retrait minimum par devise"
                    ),
                ),
                (
                    "max_withdrawal",
                    models.JSONField(
                        default=dict, verbose_name="Retrait maximum par devise"
                    ),
                ),
                (
                    "deposit_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Frais de dépôt (%)",
                    ),
                ),
                (
                    "withdrawal_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Frais de retrait (%)",
                    ),
                ),
                (
                    "deposit_fee_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais fixes de dépôt",
                    ),
                ),
                (
                    "withdrawal_fee_fixed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais fixes de retrait",
                    ),
                ),
                (
                    "deposit_processing_time",
                    models.CharField(
                        default="Instantané",
                        max_length=50,
                        verbose_name="Délai de traitement des dépôts",
                    ),
                ),
                (
                    "withdrawal_processing_time",
                    models.CharField(
                        default="24-48h",
                        max_length=50,
                        verbose_name="Délai de traitement des retraits",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payment_icons/",
                        verbose_name="Icône",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Méthode de paiement",
                "verbose_name_plural": "Méthodes de paiement",
                "db_table": "payment_methods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_withdrawal_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100000.00"),
                        max_digits=12,
                        verbose_name="Limite de retrait quotidien",
                    ),
                ),
                (
                    "monthly_withdrawal_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000000.00"),
                        max_digits=12,
                        verbose_name="Limite de retrait mensuel",
                    ),
                ),
                (
                    "deposit_usage_requirement",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("60.00"),
                        help_text="Pourcentage du dépôt qui doit être misé avant retrait",
                        max_digits=5,
                        verbose_name="Utilisation obligatoire des dépôts (%)",
                    ),
                ),
                (
                    "kyc_required_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10000.00"),
                        max_digits=10,
                        verbose_name="Montant nécessitant KYC",
                    ),
                ),
                (
                    "auto_approval_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000.00"),
                        max_digits=10,
                        verbose_name="Limite d'approbation automatique",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Paramètres de paiement",
                "verbose_name_plural": "Paramètres de paiement",
                "db_table": "payment_settings",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_currency",
                    models.CharField(max_length=5, verbose_name="Devise source"),
                ),
                (
                    "to_currency",
                    models.CharField(max_length=5, verbose_name="Devise cible"),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8, max_digits=15, verbose_name="Taux"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual", max_length=50, verbose_name="Source"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Taux de change",
                "verbose_name_plural": "Taux de change",
                "db_table": "exchange_rates",
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency"],
                        name="exchange_ra_from_cu_55f9b4_idx",
                    ),
                    models.Index(
                        fields=["updated_at"], name="exchange_ra_updated_874f6b_idx"
                    ),
                ],
                "unique_together": {("from_currency", "to_currency")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="ID de transaction",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="Référence du processeur de paiement",
                        max_length=100,
                        null=True,
                        verbose_name="Référence externe",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Dépôt"),
                            ("withdrawal", "Retrait"),
                            ("bet", "Mise"),
                            ("win", "Gain"),
                            ("commission", "Commission"),
                            ("referral", "Commission de parrainage"),
                            ("refund", "Remboursement"),
                            ("bonus", "Bonus"),
                            ("penalty", "Pénalité"),
                            ("fee", "Frais"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("FCFA", "FCFA"),
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                        ],
                        max_length=5,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Frais",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Montant net",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours de traitement"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("expired", "Expiré"),
                            ("disputed", "En litige"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Raison de l'échec"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Complété le"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="games.game",
                        verbose_name="Partie",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.paymentmethod",
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(max_length=50, verbose_name="Fournisseur"),
                ),
                (
                    "webhook_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID du webhook"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="Type d'événement"),
                ),
                ("payload", models.JSONField(verbose_name="Données")),
                (
                    "headers",
                    models.JSONField(default=dict, verbose_name="En-têtes HTTP"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processed", "Traité"),
                            ("failed", "Échoué"),
                            ("ignored", "Ignoré"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks",
                        to="payments.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook de paiement",
                "verbose_name_plural": "Webhooks de paiement",
                "db_table": "payment_webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("FCFA", "FCFA"),
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                        ],
                        max_length=5,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Solde disponible",
                    ),
                ),
                (
                    "locked_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Solde bloqué",
                    ),
                ),
                (
                    "total_deposited",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total déposé",
                    ),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total retiré",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "last_transaction_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière transaction"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portefeuille",
                "verbose_name_plural": "Portefeuilles",
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("FCFA", "FCFA"),
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                        ],
                        max_length=5,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "recipient_details",
                    models.JSONField(verbose_name="Détails du bénéficiaire"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("processing", "En cours de traitement"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes admin"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Raison du rejet"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Révisé le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.paymentmethod",
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Révisé par",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_request",
                        to="payments.transaction",
                        verbose_name="Transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de retrait",
                "verbose_name_plural": "Demandes de retrait",
                "db_table": "withdrawal_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "created_at"], name="transaction_user_id_294647_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "status"],
                name="transaction_transac_9f5934_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "created_at"], name="transaction_status_94cf9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["external_reference"], name="transaction_externa_9dc24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_id"], name="transaction_transac_5011c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhook",
            index=models.Index(
                fields=["provider", "event_type"], name="payment_web_provide_e7082c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhook",
            index=models.Index(
                fields=["status", "created_at"], name="payment_web_status_8d2828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhook",
            index=models.Index(
                fields=["webhook_id"], name="payment_web_webhook_83caa2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["user", "currency"], name="wallets_user_id_84225e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("user", "currency")},
        ),
    ]
