# Generated by Django migration for payment methods initialization

from django.db import migrations
from decimal import Decimal


def create_payment_methods(apps, schema_editor):
    """Créer les méthodes de paiement de base."""
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')
    
    # Méthodes de paiement avec seulement les champs existants
    payment_methods = [
        {
            'name': 'Orange Money',
            'method_type': 'mobile_money',
            'supported_currencies': ['FCFA'],
            'min_deposit': {'FCFA': 500},
            'max_deposit': {'FCFA': 500000},
            'min_withdrawal': {'FCFA': 1000},
            'max_withdrawal': {'FCFA': 250000},
            'deposit_fee_percentage': Decimal('1.5'),
            'withdrawal_fee_percentage': Decimal('2.0'),
            'deposit_fee_fixed': Decimal('0'),
            'withdrawal_fee_fixed': Decimal('100'),
            'is_active': True,
            'description': 'Paiement mobile via Orange Money'
        },
        {
            'name': 'MTN Mobile Money',
            'method_type': 'mobile_money',
            'supported_currencies': ['FCFA'],
            'min_deposit': {'FCFA': 500},
            'max_deposit': {'FCFA': 500000},
            'min_withdrawal': {'FCFA': 1000},
            'max_withdrawal': {'FCFA': 250000},
            'deposit_fee_percentage': Decimal('1.5'),
            'withdrawal_fee_percentage': Decimal('2.0'),
            'deposit_fee_fixed': Decimal('0'),
            'withdrawal_fee_fixed': Decimal('100'),
            'is_active': True,
            'description': 'Paiement mobile via MTN Mobile Money'
        },
        {
            'name': 'Moov Money',
            'method_type': 'mobile_money',
            'supported_currencies': ['FCFA'],
            'min_deposit': {'FCFA': 500},
            'max_deposit': {'FCFA': 500000},
            'min_withdrawal': {'FCFA': 1000},
            'max_withdrawal': {'FCFA': 250000},
            'deposit_fee_percentage': Decimal('1.5'),
            'withdrawal_fee_percentage': Decimal('2.0'),
            'deposit_fee_fixed': Decimal('0'),
            'withdrawal_fee_fixed': Decimal('100'),
            'is_active': True,
            'description': 'Paiement mobile via Moov Money'
        },
        {
            'name': 'Carte Bancaire',
            'method_type': 'card',
            'supported_currencies': ['EUR', 'USD', 'FCFA'],
            'min_deposit': {'EUR': 5, 'USD': 5, 'FCFA': 3000},
            'max_deposit': {'EUR': 5000, 'USD': 5000, 'FCFA': 3000000},
            'min_withdrawal': {'EUR': 10, 'USD': 10, 'FCFA': 6000},
            'max_withdrawal': {'EUR': 2000, 'USD': 2000, 'FCFA': 1200000},
            'deposit_fee_percentage': Decimal('2.9'),
            'withdrawal_fee_percentage': Decimal('3.5'),
            'deposit_fee_fixed': Decimal('0.30'),
            'withdrawal_fee_fixed': Decimal('1.00'),
            'is_active': True,
            'description': 'Paiement par carte bancaire Visa/MasterCard'
        },
        {
            'name': 'Virement Bancaire',
            'method_type': 'bank_transfer',
            'supported_currencies': ['EUR', 'USD', 'FCFA'],
            'min_deposit': {'EUR': 20, 'USD': 20, 'FCFA': 15000},
            'max_deposit': {'EUR': 10000, 'USD': 10000, 'FCFA': 6000000},
            'min_withdrawal': {'EUR': 50, 'USD': 50, 'FCFA': 30000},
            'max_withdrawal': {'EUR': 5000, 'USD': 5000, 'FCFA': 3000000},
            'deposit_fee_percentage': Decimal('0.5'),
            'withdrawal_fee_percentage': Decimal('1.0'),
            'deposit_fee_fixed': Decimal('2.00'),
            'withdrawal_fee_fixed': Decimal('5.00'),
            'is_active': False,  # Désactivé par défaut
            'description': 'Virement bancaire SEPA/International'
        }
    ]
    
    # Créer les méthodes de paiement
    for method_data in payment_methods:
        PaymentMethod.objects.get_or_create(
            name=method_data['name'],
            defaults=method_data
        )


def reverse_payment_methods(apps, schema_editor):
    """Supprimer les méthodes de paiement créées."""
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')
    
    method_names = [
        'Orange Money',
        'MTN Mobile Money', 
        'Moov Money',
        'Carte Bancaire',
        'Virement Bancaire'
    ]
    
    PaymentMethod.objects.filter(name__in=method_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_feexpay_models'),
    ]

    operations = [
        migrations.RunPython(
            create_payment_methods,
            reverse_payment_methods,
            elidable=True,
        ),
    ]