# Generated by Django 4.2.7 on 2025-11-15 18:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_feexpay_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feexpayprovider',
            name='feexpay_provider_country_unique',
        ),
        migrations.RenameIndex(
            model_name='feexpaytransaction',
            new_name='feexpay_tra_user_id_526a05_idx',
            old_name='feexpay_transactions_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='feexpaytransaction',
            new_name='feexpay_tra_status_84d403_idx',
            old_name='feexpay_transactions_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='feexpaytransaction',
            new_name='feexpay_tra_feexpay_4c9c40_idx',
            old_name='feexpay_transactions_feexpay_id_idx',
        ),
        migrations.RenameIndex(
            model_name='feexpaytransaction',
            new_name='feexpay_tra_interna_90a9ed_idx',
            old_name='feexpay_transactions_internal_id_idx',
        ),
        migrations.RenameIndex(
            model_name='feexpaytransaction',
            new_name='feexpay_tra_provide_4d8d66_idx',
            old_name='feexpay_transactions_provider_status_idx',
        ),
        migrations.RenameIndex(
            model_name='feexpaywebhooksignature',
            new_name='feexpay_web_webhook_3fcc4a_idx',
            old_name='feexpay_webhooks_webhook_id_idx',
        ),
        migrations.RenameIndex(
            model_name='feexpaywebhooksignature',
            new_name='feexpay_web_is_vali_dd8b13_idx',
            old_name='feexpay_webhooks_valid_processed_idx',
        ),
        migrations.RenameIndex(
            model_name='feexpaywebhooksignature',
            new_name='feexpay_web_event_t_917464_idx',
            old_name='feexpay_webhooks_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='feexpaywebhooksignature',
            new_name='feexpay_web_receive_4b772f_idx',
            old_name='feexpay_webhooks_received_at_idx',
        ),
        migrations.AlterField(
            model_name='feexpayprovider',
            name='fee_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Frais fixes'),
        ),
        migrations.AlterField(
            model_name='feexpayprovider',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Frais (%)'),
        ),
        migrations.AlterField(
            model_name='feexpayprovider',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=12, verbose_name='Montant maximum'),
        ),
        migrations.AlterField(
            model_name='feexpayprovider',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, verbose_name='Montant minimum'),
        ),
        migrations.AlterField(
            model_name='feexpayprovider',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Taux de réussite (%)'),
        ),
        migrations.AlterField(
            model_name='feexpayprovider',
            name='total_volume',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Volume total'),
        ),
        migrations.AlterField(
            model_name='feexpaytransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='feexpaytransaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant des frais'),
        ),
        migrations.AlterField(
            model_name='feexpaytransaction',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant brut (montant + frais)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withwithdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par'),
        ),
        migrations.AlterUniqueTogether(
            name='feexpayprovider',
            unique_together={('provider_code', 'country_code')},
        ),
    ]
