# Generated by Django 4.2.7 on 2025-11-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_init_payment_methods'),
        ('payments', '0005_remove_feexpayprovider_feexpay_provider_country_unique_and_more'),
    ]

    operations = [
    ]
