# Generated by Django 4.2.7 on 2025-11-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_feexpay_withdrawal'),
        ('payments', '0006_merge_20251118_0834'),
    ]

    operations = [
    ]
