# Generated by Django 4.2.8 on 2025-12-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_initial"),
        ("common", "0002_alter_notification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="audittrail",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_trails",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="filestorage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_files",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="systemlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_logs",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Administrateur"),
                    ("ADMIN", "Administrateur Système"),
                    ("MANAGER", "Manager Opérations"),
                    ("COMPTABLE", "Comptable / Manager Finance"),
                    ("GUICHETIER", "Guichetier"),
                    ("CHAUFFEUR", "Chauffeur"),
                    ("CONTROLEUR", "Contrôleur"),
                    ("GESTIONNAIRE_COURRIER", "Gestionnaire Courrier"),
                ],
                db_index=True,
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("module", "code")},
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="common_audi_model_n_f641ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["user", "action"], name="common_audi_user_id_2bf0fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["timestamp"], name="common_audi_timesta_57d6ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["latitude", "longitude"], name="common_loca_latitud_4826e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["city_name"], name="common_loca_city_na_ae42b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="common_noti_user_id_aae5b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="common_noti_created_dff411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["level", "timestamp"], name="common_syst_level_9e6215_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemlog",
            index=models.Index(
                fields=["module", "timestamp"], name="common_syst_module_b29cd8_idx"
            ),
        ),
    ]
