# Generated by Django 4.2.8 on 2025-12-27 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_initial"),
    ]

    operations = []
