# Generated by Django 5.2.6 on 2025-09-25 08:47

import apps.accounts.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format de numéro invalide. Ex: +33612345678",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Pays"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Adresse complète"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                            ("zh", "中文"),
                        ],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue préférée",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="Fuseau horaire"
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[("FCFA", "FCFA"), ("EUR", "EUR"), ("USD", "USD")],
                        default="FCFA",
                        max_length=5,
                        verbose_name="Devise préférée",
                    ),
                ),
                (
                    "balance_fcfa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Solde FCFA",
                    ),
                ),
                (
                    "balance_eur",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Solde EUR",
                    ),
                ),
                (
                    "balance_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Solde USD",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Email vérifié"),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("under_review", "En cours de vérification"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("expired", "Expiré"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut KYC",
                    ),
                ),
                (
                    "kyc_submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="KYC soumis le"
                    ),
                ),
                (
                    "kyc_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="KYC vérifié le"
                    ),
                ),
                (
                    "kyc_rejection_reason",
                    models.TextField(blank=True, verbose_name="Raison du rejet KYC"),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True,
                        help_text="Code unique pour parrainer d'autres utilisateurs",
                        max_length=10,
                        unique=True,
                        verbose_name="Code de parrainage",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dernière IP de connexion"
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tentatives de connexion échouées"
                    ),
                ),
                (
                    "account_locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Compte verrouillé jusqu'au"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "auto_match",
                    models.BooleanField(
                        default=True,
                        help_text="Rejoindre automatiquement les parties disponibles",
                        verbose_name="Matchmaking automatique",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Parrainé par",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "Carte d'identité"),
                            ("passport", "Passeport"),
                            ("driving_license", "Permis de conduire"),
                            ("proof_of_address", "Justificatif de domicile"),
                            ("selfie", "Selfie avec pièce d'identité"),
                            ("bank_statement", "Relevé bancaire"),
                            ("utility_bill", "Facture de services publics"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Formats acceptés: JPG, PNG, PDF (max 5MB)",
                        upload_to=apps.accounts.models.KYCDocument.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"],
                                message="Seuls les fichiers JPG, PNG et PDF sont acceptés",
                            )
                        ],
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Nom du fichier original",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (bytes)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("expired", "Expiré"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Raison du rejet"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploadé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document KYC",
                "verbose_name_plural": "Documents KYC",
                "db_table": "kyc_documents",
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type d'appareil"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localisation"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=True, verbose_name="Connexion réussie"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de connexion"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de connexion",
                "verbose_name_plural": "Historiques de connexion",
                "db_table": "login_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("signup", "Inscription"),
                            ("email_verified", "Email vérifié"),
                            ("password_changed", "Mot de passe changé"),
                            ("profile_updated", "Profil mis à jour"),
                            ("kyc_submitted", "KYC soumis"),
                            ("kyc_status_changed", "Statut KYC changé"),
                            ("balance_updated", "Solde mis à jour"),
                            ("account_locked", "Compte verrouillé"),
                            ("account_unlocked", "Compte déverrouillé"),
                            ("game_created", "Partie créée"),
                            ("game_joined", "Partie rejointe"),
                            ("game_won", "Partie gagnée"),
                            ("game_lost", "Partie perdue"),
                            ("deposit_requested", "Dépôt demandé"),
                            ("deposit_completed", "Dépôt complété"),
                            ("withdrawal_requested", "Retrait demandé"),
                            ("withdrawal_completed", "Retrait complété"),
                        ],
                        max_length=30,
                        verbose_name="Type d'activité",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID de session"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité utilisateur",
                "verbose_name_plural": "Activités utilisateur",
                "db_table": "user_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("es", "Español"),
                            ("zh", "中文"),
                        ],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("FCFA", "FCFA"), ("EUR", "EUR"), ("USD", "USD")],
                        default="FCFA",
                        max_length=5,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="Fuseau horaire"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Clair"), ("dark", "Sombre")],
                        default="light",
                        max_length=20,
                        verbose_name="Thème",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications email"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications push"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="Notifications SMS"
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(default=False, verbose_name="Emails marketing"),
                ),
                (
                    "game_sounds",
                    models.BooleanField(default=True, verbose_name="Sons du jeu"),
                ),
                (
                    "auto_play",
                    models.BooleanField(default=False, verbose_name="Jeu automatique"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférences utilisateur",
                "verbose_name_plural": "Préférences utilisateur",
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Biographie"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Profil vérifié"),
                ),
                (
                    "verification_level",
                    models.CharField(
                        default="basic",
                        max_length=20,
                        verbose_name="Niveau de vérification",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateur",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir des notifications par email",
                        verbose_name="Notifications par email",
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="Recevoir des notifications par SMS",
                        verbose_name="Notifications par SMS",
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir des notifications push sur le navigateur",
                        verbose_name="Notifications push",
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False,
                        help_text="Recevoir des offres promotionnelles",
                        verbose_name="Emails marketing",
                    ),
                ),
                (
                    "login_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Être notifié des nouvelles connexions",
                        verbose_name="Notifications de connexion",
                    ),
                ),
                (
                    "auto_accept_games",
                    models.BooleanField(
                        default=False,
                        help_text="Accepter automatiquement les invitations de parties",
                        verbose_name="Accepter automatiquement les parties",
                    ),
                ),
                (
                    "show_game_tips",
                    models.BooleanField(
                        default=True,
                        help_text="Afficher des conseils pendant le jeu",
                        verbose_name="Afficher les conseils de jeu",
                    ),
                ),
                (
                    "sound_effects",
                    models.BooleanField(
                        default=True,
                        help_text="Activer les sons du jeu",
                        verbose_name="Effets sonores",
                    ),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Activer l'authentification à deux facteurs",
                        verbose_name="Authentification à deux facteurs",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres utilisateur",
                "verbose_name_plural": "Paramètres utilisateur",
                "db_table": "user_settings",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["referral_code"], name="users_referra_98b351_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["kyc_status"], name="users_kyc_sta_4052e1_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["country"], name="users_country_122a0c_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_verified", "kyc_status"], name="users_is_veri_64e453_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("balance_fcfa__gte", 0)),
                name="positive_balance_fcfa",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("balance_eur__gte", 0)), name="positive_balance_eur"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("balance_usd__gte", 0)), name="positive_balance_usd"
            ),
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(
                fields=["user", "status"], name="kyc_documen_user_id_19faeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(
                fields=["status", "created_at"], name="kyc_documen_status_d38120_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycdocument",
            index=models.Index(
                fields=["document_type"], name="kyc_documen_documen_9c13cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kycdocument",
            unique_together={("user", "document_type")},
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="login_histo_user_id_9416b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["ip_address"], name="login_histo_ip_addr_3ce48d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["-created_at"], name="login_histo_created_c05933_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "-created_at"], name="user_activi_user_id_47a698_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type", "-created_at"],
                name="user_activi_activit_b9defd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["ip_address"], name="user_activi_ip_addr_ebdeb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["-created_at"], name="user_activi_created_5315c9_idx"
            ),
        ),
    ]
