# Generated by Django 4.2.7 on 2025-11-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='kyc_banner_dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC banner dismissed at'),
        ),
    ]
