# Generated by Django 5.2.6 on 2025-09-25 06:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Nom d'affichage"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strategy", "Stratégie"),
                            ("cards", "Cartes"),
                            ("board", "Plateau"),
                            ("puzzle", "Puzzle"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "min_players",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Joueurs minimum"
                    ),
                ),
                (
                    "max_players",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Joueurs maximum"
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Durée estimée (minutes)"
                    ),
                ),
                (
                    "min_bet_fcfa",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        max_digits=10,
                        verbose_name="Mise minimum FCFA",
                    ),
                ),
                (
                    "max_bet_fcfa",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000000,
                        max_digits=10,
                        verbose_name="Mise maximum FCFA",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="game_icons/",
                        verbose_name="Icône",
                    ),
                ),
                (
                    "rules_url",
                    models.URLField(blank=True, verbose_name="Lien vers les règles"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Type de jeu",
                "verbose_name_plural": "Types de jeux",
                "db_table": "game_types",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        unique=True,
                        verbose_name="Code de partie",
                    ),
                ),
                (
                    "bet_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant de la mise",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("FCFA", "FCFA"), ("EUR", "EUR"), ("USD", "USD")],
                        default="FCFA",
                        max_length=5,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "total_pot",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Cagnotte totale",
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Commission",
                    ),
                ),
                (
                    "winner_prize",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Prix du gagnant",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "En attente d'un joueur"),
                            ("ready", "Prêt à commencer"),
                            ("playing", "En cours"),
                            ("paused", "En pause"),
                            ("finished", "Terminé"),
                            ("cancelled", "Annulé"),
                            ("disputed", "En litige"),
                            ("abandoned", "Abandonné"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "game_data",
                    models.JSONField(default=dict, verbose_name="Données de la partie"),
                ),
                (
                    "move_history",
                    models.JSONField(default=list, verbose_name="Historique des coups"),
                ),
                (
                    "turn_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Début du tour"
                    ),
                ),
                (
                    "turn_timeout",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Timeout du tour (secondes)"
                    ),
                ),
                (
                    "player1_time_left",
                    models.PositiveIntegerField(
                        default=600, verbose_name="Temps restant J1 (secondes)"
                    ),
                ),
                (
                    "player2_time_left",
                    models.PositiveIntegerField(
                        default=600, verbose_name="Temps restant J2 (secondes)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Commencé le"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "last_move_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier coup le"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="Partie privée"),
                ),
                (
                    "is_rated",
                    models.BooleanField(default=True, verbose_name="Partie classée"),
                ),
                (
                    "spectators_allowed",
                    models.BooleanField(
                        default=True, verbose_name="Spectateurs autorisés"
                    ),
                ),
                (
                    "current_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_games",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Joueur actuel",
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_player1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Joueur 1",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_player2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Joueur 2",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_games",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gagnant",
                    ),
                ),
                (
                    "game_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="games.gametype",
                        verbose_name="Type de jeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partie",
                "verbose_name_plural": "Parties",
                "db_table": "games",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("cheating", "Triche"),
                            ("inappropriate_behavior", "Comportement inapproprié"),
                            ("harassment", "Harcèlement"),
                            ("technical_issue", "Problème technique"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Type de signalement",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "evidence",
                    models.JSONField(blank=True, default=dict, verbose_name="Preuves"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("under_review", "En cours de traitement"),
                            ("resolved", "Résolu"),
                            ("dismissed", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Notes admin"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Résolu le"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="games.game",
                        verbose_name="Partie",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur signalé",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signalant",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Résolu par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signalement de partie",
                "verbose_name_plural": "Signalements de parties",
                "db_table": "game_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("monthly", "Mensuel"),
                            ("weekly", "Hebdomadaire"),
                            ("game_type", "Par type de jeu"),
                        ],
                        max_length=20,
                        verbose_name="Type de classement",
                    ),
                ),
                ("rank", models.PositiveIntegerField(verbose_name="Rang")),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="Points"),
                ),
                (
                    "games_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Parties jouées"
                    ),
                ),
                (
                    "games_won",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Parties gagnées"
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Taux de victoire",
                    ),
                ),
                (
                    "total_winnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Gains totaux",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "game_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="games.gametype",
                        verbose_name="Type de jeu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classement",
                "verbose_name_plural": "Classements",
                "db_table": "leaderboards",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("single_elimination", "Élimination directe"),
                            ("double_elimination", "Double élimination"),
                            ("round_robin", "Round robin"),
                            ("swiss", "Système suisse"),
                        ],
                        max_length=20,
                        verbose_name="Type de tournoi",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(verbose_name="Participants maximum"),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Frais d'inscription",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("FCFA", "FCFA"), ("EUR", "EUR"), ("USD", "USD")],
                        default="FCFA",
                        max_length=5,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "total_prize_pool",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Cagnotte totale",
                    ),
                ),
                (
                    "winner_prize",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix du gagnant",
                    ),
                ),
                (
                    "runner_up_prize",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Prix du finaliste",
                    ),
                ),
                (
                    "registration_start",
                    models.DateTimeField(verbose_name="Début des inscriptions"),
                ),
                (
                    "registration_end",
                    models.DateTimeField(verbose_name="Fin des inscriptions"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "À venir"),
                            ("registration", "Inscriptions ouvertes"),
                            ("ready", "Prêt à commencer"),
                            ("ongoing", "En cours"),
                            ("finished", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "game_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="games.gametype",
                        verbose_name="Type de jeu",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_tournaments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournoi",
                "verbose_name_plural": "Tournois",
                "db_table": "tournaments",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seed",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tête de série"
                    ),
                ),
                (
                    "current_round",
                    models.PositiveIntegerField(default=1, verbose_name="Tour actuel"),
                ),
                (
                    "is_eliminated",
                    models.BooleanField(default=False, verbose_name="Éliminé"),
                ),
                (
                    "final_position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Position finale"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inscrit le"),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="games.tournament",
                        verbose_name="Tournoi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant au tournoi",
                "verbose_name_plural": "Participants aux tournois",
                "db_table": "tournament_participants",
            },
        ),
        migrations.CreateModel(
            name="GameInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("declined", "Refusée"),
                            ("expired", "Expirée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Répondu le"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="games.game",
                        verbose_name="Partie",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invité",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invitant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation de partie",
                "verbose_name_plural": "Invitations de parties",
                "db_table": "game_invitations",
                "unique_together": {("game", "invitee")},
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["status", "created_at"], name="games_status_1725dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["player1", "created_at"], name="games_player1_6ab93e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["player2", "created_at"], name="games_player2_2f0e40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["room_code"], name="games_room_co_0de2cb_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["game_type", "status"], name="games_game_ty_84ba67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["leaderboard_type", "rank"],
                name="leaderboard_leaderb_d3b7b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["game_type", "rank"], name="leaderboard_game_ty_d75555_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboard",
            index=models.Index(
                fields=["user", "leaderboard_type"],
                name="leaderboard_user_id_5225e9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentparticipant",
            unique_together={("tournament", "user")},
        ),
    ]
