# Generated by Django 4.2.7 on 2025-12-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player1_time_left",
            field=models.PositiveIntegerField(
                default=21000, verbose_name="Temps restant J1 (secondes)"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player2_time_left",
            field=models.PositiveIntegerField(
                default=21000, verbose_name="Temps restant J2 (secondes)"
            ),
        ),
    ]
