# Generated by Django 4.2.8 on 2025-12-27 14:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        ("users", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("recipient_name", models.CharField(max_length=100)),
                ("recipient_phone", models.CharField(max_length=20)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("description", models.TextField()),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Longueur x Largeur x Hauteur",
                        max_length=100,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "weight_surcharge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "fragile_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Accepté"),
                            ("IN_TRANSIT", "En transit"),
                            ("DELIVERED", "Livré"),
                            ("LOST", "Perdu"),
                            ("RETURNED", "Retourné"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_fragile", models.BooleanField(default=False)),
                ("requires_signature", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_notes", models.TextField(blank=True)),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("is_insured", models.BooleanField(default=False)),
                (
                    "insurance_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "insurance_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Colis",
                "verbose_name_plural": "Colis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParcelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("is_fragile", models.BooleanField(default=False)),
                ("requires_signature", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Catégorie de colis",
                "verbose_name_plural": "Catégories de colis",
            },
        ),
        migrations.CreateModel(
            name="ParcelInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "coverage_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage de couverture",
                        max_digits=5,
                    ),
                ),
                (
                    "max_coverage_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("base_fee", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Assurance colis",
                "verbose_name_plural": "Assurances colis",
            },
        ),
        migrations.CreateModel(
            name="ParcelTracking",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCANNED", "Numérisé"),
                            ("COLLECTED", "Collecté"),
                            ("IN_TRANSIT", "En transit"),
                            ("OUT_FOR_DELIVERY", "Livraison en cours"),
                            ("DELIVERED", "Livré"),
                            ("FAILED", "Tentative échouée"),
                            ("RETURNED", "Retourné"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parcel_tracking_updates",
                        to="users.user",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_history",
                        to="parcels.parcel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de colis",
                "verbose_name_plural": "Suivis de colis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="parcel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parcels.parcelcategory",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_parcels",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parcels",
                to="trips.trip",
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["tracking_number"], name="parcels_par_trackin_9fa642_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["status", "created_at"], name="parcels_par_status_be4704_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["trip", "status"], name="parcels_par_trip_id_22bb73_idx"
            ),
        ),
    ]
