# Generated by Django 4.2.8 on 2025-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("recipient_name", models.CharField(max_length=100)),
                ("recipient_phone", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("IN_TRANSIT", "En transit"),
                            ("DELIVERED", "Livré"),
                            ("LOST", "Perdu"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Colis",
                "verbose_name_plural": "Colis",
                "ordering": ["-created_at"],
            },
        ),
    ]
