# Generated by Django 4.2.8 on 2025-12-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("parcels", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_parcels",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parcels",
                to="trips.trip",
            ),
        ),
    ]
