# Generated by Django 4.2.8 on 2025-12-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.location",
                    ),
                ),
                ("population", models.IntegerField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Ville",
                "verbose_name_plural": "Villes",
                "ordering": ["name"],
            },
            bases=("common.location",),
        ),
    ]
