# Generated by Django 4.2.8 on 2025-12-25 00:03

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default='UND', help_text='Code postal ou code de la ville', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de la ville', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='has_parking',
            field=models.BooleanField(default=False, help_text='Disponibilité d\'un parking'),
        ),
        migrations.AddField(
            model_name='city',
            name='has_terminal',
            field=models.BooleanField(default=False, help_text='Disponibilité d\'un terminal'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_hub',
            field=models.BooleanField(default=False, help_text='Indique si c\'est un hub majeur'),
        ),
        migrations.AddField(
            model_name='city',
            name='trip_count',
            field=models.IntegerField(default=0, help_text='Nombre de trajets'),
        ),
        migrations.AddField(
            model_name='city',
            name='annual_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Chiffre d\'affaires annuel (CFA)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(blank=True, help_text='Population de la ville', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, help_text='Région administrative', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['region'], name='cities_city_region_478c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_hub'], name='cities_city_is_hub_1819d7_idx'),
        ),
    ]
