# Generated by Django 4.2.8 on 2025-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "employee_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("DRIVER", "Chauffeurs"),
                            ("OPERATIONS", "Opérations"),
                            ("ADMIN", "Administration"),
                            ("SUPPORT", "Support"),
                        ],
                        max_length=50,
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("hire_date", models.DateField()),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["employee_id"],
            },
        ),
    ]
