# Generated by Django 4.2.8 on 2025-12-27 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("first_name", models.CharField(db_index=True, max_length=100)),
                ("last_name", models.CharField(db_index=True, max_length=100)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("driver", "Chauffeur"),
                            ("receiver", "Receveur"),
                            ("cashier", "Guichetier"),
                            ("controller", "Contrôleur"),
                            ("mail_agent", "Agent Courrier"),
                            ("admin", "Administrateur"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salaire mensuel de base en FCFA",
                        max_digits=12,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pourcentage de commission (ex: 5.00 pour 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("on_leave", "En congé"),
                            ("suspended", "Suspendu"),
                            ("retired", "Retraité"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "document_type",
                    models.CharField(
                        default="national_id",
                        help_text="Type de document d'identité",
                        max_length=50,
                    ),
                ),
                (
                    "document_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("document_expiry", models.DateField(blank=True, null=True)),
                (
                    "trips_completed",
                    models.IntegerField(
                        default=0, help_text="Nombre de trajets effectués"
                    ),
                ),
                (
                    "parcels_delivered",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre de colis livrés (pour agents courrier)",
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Revenus totaux cumulés",
                        max_digits=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePerformance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("evaluation_date", models.DateField()),
                (
                    "punctuality",
                    models.IntegerField(
                        choices=[
                            (1, "Très mauvais"),
                            (2, "Mauvais"),
                            (3, "Moyen"),
                            (4, "Bon"),
                            (5, "Très bon"),
                        ],
                        help_text="Ponctualité et assiduité",
                    ),
                ),
                (
                    "professionalism",
                    models.IntegerField(
                        choices=[
                            (1, "Très mauvais"),
                            (2, "Mauvais"),
                            (3, "Moyen"),
                            (4, "Bon"),
                            (5, "Très bon"),
                        ],
                        help_text="Professionnalisme et comportement",
                    ),
                ),
                (
                    "quality_of_work",
                    models.IntegerField(
                        choices=[
                            (1, "Très mauvais"),
                            (2, "Mauvais"),
                            (3, "Moyen"),
                            (4, "Bon"),
                            (5, "Très bon"),
                        ],
                        help_text="Qualité du travail effectué",
                    ),
                ),
                (
                    "teamwork",
                    models.IntegerField(
                        choices=[
                            (1, "Très mauvais"),
                            (2, "Mauvais"),
                            (3, "Moyen"),
                            (4, "Bon"),
                            (5, "Très bon"),
                        ],
                        help_text="Capacité à travailler en équipe",
                    ),
                ),
                (
                    "initiative",
                    models.IntegerField(
                        choices=[
                            (1, "Très mauvais"),
                            (2, "Mauvais"),
                            (3, "Moyen"),
                            (4, "Bon"),
                            (5, "Très bon"),
                        ],
                        help_text="Prise d'initiative et créativité",
                    ),
                ),
                (
                    "overall_rating",
                    models.FloatField(help_text="Note moyenne de performance"),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="employees.employee",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_given",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation de performance",
                "verbose_name_plural": "Évaluations de performance",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeLeave",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Congé annuel"),
                            ("sick", "Congé maladie"),
                            ("maternity", "Congé maternité"),
                            ("unpaid", "Congé non payé"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "duration_days",
                    models.IntegerField(help_text="Nombre de jours de congé"),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leaves_approved",
                        to="users.user",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Congé employé",
                "verbose_name_plural": "Congés employés",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeePayroll",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("year", models.IntegerField(db_index=True)),
                ("month", models.IntegerField(db_index=True)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "social_security",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "advance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("paid", "Payé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Mobile Money, Virement, etc.",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de paie",
                "verbose_name_plural": "Fiches de paie",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["employee", "year", "month"],
                        name="employees_e_employe_2e0ddd_idx",
                    )
                ],
                "unique_together": {("employee", "year", "month")},
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["role", "status"], name="employees_e_role_560693_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["hire_date"], name="employees_e_hire_da_c2151e_idx"
            ),
        ),
    ]
