# Generated by Django 4.2.8 on 2025-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "registration_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BUS", "Bus"),
                            ("MINIBUS", "Minibus"),
                            ("TRUCK", "Camion"),
                            ("VAN", "Van"),
                        ],
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
                "ordering": ["registration_number"],
            },
        ),
    ]
