# Generated by Django 4.2.8 on 2025-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("seat_number", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponible"),
                            ("BOOKED", "Réservé"),
                            ("CONFIRMED", "Confirmé"),
                            ("USED", "Utilisé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Billet",
                "verbose_name_plural": "Billets",
                "ordering": ["-created_at"],
            },
        ),
    ]
