# Generated by Django 4.2.8 on 2025-12-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        ("users", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="trips.trip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("trip", "seat_number")},
        ),
    ]
