# Generated by Django 5.2.6 on 2025-09-25 06:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du programme"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("fixed", "Montant fixe"),
                            ("tiered", "Par paliers"),
                        ],
                        max_length=20,
                        verbose_name="Type de commission",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("50.00")),
                        ],
                        verbose_name="Taux de commission (%)",
                    ),
                ),
                (
                    "fixed_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Commission fixe",
                    ),
                ),
                (
                    "max_commission_per_referral",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="0 = illimité",
                        max_digits=10,
                        verbose_name="Commission max par filleul",
                    ),
                ),
                (
                    "max_daily_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="0 = illimité",
                        max_digits=10,
                        verbose_name="Commission quotidienne max",
                    ),
                ),
                (
                    "max_monthly_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="0 = illimité",
                        max_digits=12,
                        verbose_name="Commission mensuelle max",
                    ),
                ),
                (
                    "min_bet_for_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=10,
                        verbose_name="Mise minimum pour commission",
                    ),
                ),
                (
                    "free_games_limit",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Nombre de parties donnant commission pour utilisateurs non premium",
                        verbose_name="Limite de parties gratuites",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("paused", "En pause"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Programme par défaut"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
            ],
            options={
                "verbose_name": "Programme de parrainage",
                "verbose_name_plural": "Programmes de parrainage",
                "db_table": "referral_programs",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_commission_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Commission totale gagnée",
                    ),
                ),
                (
                    "games_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Parties jouées"
                    ),
                ),
                (
                    "commission_games_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Parties ayant généré une commission"
                    ),
                ),
                (
                    "last_commission_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière commission"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("suspended", "Suspendu"),
                            ("expired", "Expiré"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_premium_referrer",
                    models.BooleanField(default=False, verbose_name="Parrain premium"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "referred",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Filleul",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Parrain",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="referrals.referralprogram",
                        verbose_name="Programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parrainage",
                "verbose_name_plural": "Parrainages",
                "db_table": "referrals",
            },
        ),
        migrations.CreateModel(
            name="ReferralBonus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("signup", "Bonus d'inscription"),
                            ("first_deposit", "Premier dépôt"),
                            ("milestone", "Palier atteint"),
                            ("loyalty", "Fidélité"),
                            ("special", "Événement spécial"),
                        ],
                        max_length=20,
                        verbose_name="Type de bonus",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="FCFA", max_length=5, verbose_name="Devise"
                    ),
                ),
                (
                    "minimum_bet_requirement",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Mise minimum requise",
                    ),
                ),
                (
                    "wagering_requirement",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre de fois que le bonus doit être misé",
                        verbose_name="Exigence de mise (x fois)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("claimed", "Réclamé"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Réclamé le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="referrals.referral",
                        verbose_name="Parrainage",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_bonus",
                        to="payments.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bonus de parrainage",
                "verbose_name_plural": "Bonus de parrainage",
                "db_table": "referral_bonuses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                            ("yearly", "Annuel"),
                        ],
                        max_length=20,
                        verbose_name="Type de période",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "total_referrals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total filleuls"
                    ),
                ),
                (
                    "active_referrals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Filleuls actifs"
                    ),
                ),
                (
                    "new_referrals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nouveaux filleuls"
                    ),
                ),
                (
                    "total_games_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Parties jouées"
                    ),
                ),
                (
                    "commission_games",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Parties avec commission"
                    ),
                ),
                (
                    "total_commission_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Commission totale",
                    ),
                ),
                (
                    "total_bet_volume",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Volume de mises",
                    ),
                ),
                (
                    "average_commission_per_game",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Commission moyenne par partie",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_statistics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statistiques de parrainage",
                "verbose_name_plural": "Statistiques de parrainage",
                "db_table": "referral_statistics",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="PremiumSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensuel"),
                            ("quarterly", "Trimestriel"),
                            ("yearly", "Annuel"),
                            ("lifetime", "À vie"),
                        ],
                        max_length=20,
                        verbose_name="Type de plan",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="FCFA", max_length=5, verbose_name="Devise"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "auto_renewal",
                    models.BooleanField(
                        default=False, verbose_name="Renouvellement automatique"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                            ("suspended", "Suspendu"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Annulé le"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="premium_subscription",
                        to="payments.transaction",
                        verbose_name="Transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement premium",
                "verbose_name_plural": "Abonnements premium",
                "db_table": "premium_subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="premium_sub_user_id_7ba085_idx"
                    ),
                    models.Index(
                        fields=["end_date", "status"],
                        name="premium_sub_end_dat_15def0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferralCommission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant de la commission",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="FCFA", max_length=5, verbose_name="Devise"
                    ),
                ),
                (
                    "referrer_balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Solde du parrain avant",
                    ),
                ),
                (
                    "referrer_balance_after",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Solde du parrain après",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Payée"),
                            ("cancelled", "Annulée"),
                            ("failed", "Échoué"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, verbose_name="Raison de l'échec"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_commissions",
                        to="games.game",
                        verbose_name="Partie",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="referrals.referral",
                        verbose_name="Parrainage",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_commission",
                        to="payments.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission de parrainage",
                "verbose_name_plural": "Commissions de parrainage",
                "db_table": "referral_commissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["referral", "created_at"],
                        name="referral_co_referra_810a07_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="referral_co_status_3e5c52_idx",
                    ),
                    models.Index(
                        fields=["game"], name="referral_co_game_id_09f9b3_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referrer", "status"], name="referrals_referre_cefb5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referred"], name="referrals_referre_e2a62f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["created_at"], name="referrals_created_995256_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referral",
            unique_together={("referrer", "referred")},
        ),
        migrations.AddIndex(
            model_name="referralstatistics",
            index=models.Index(
                fields=["user", "period_type"], name="referral_st_user_id_d57c68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralstatistics",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="referral_st_period__e09ccf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referralstatistics",
            unique_together={("user", "period_type", "period_start")},
        ),
    ]
