# Generated by Django 4.2.7 on 2025-12-22 09:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code unique pour le parrainage",
                        max_length=20,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "share_url",
                    models.URLField(
                        blank=True,
                        help_text="URL complet pour partager le code",
                        verbose_name="URL du code",
                    ),
                ),
                (
                    "share_channels",
                    models.CharField(
                        blank=True,
                        help_text="Canaux par lesquels ce code a été partagé",
                        max_length=255,
                        verbose_name="Canaux de partage",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = illimité",
                        verbose_name="Utilisations maximales",
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Utilisations actuelles"
                    ),
                ),
                (
                    "min_first_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant minimum à déposer après inscription via le code",
                        max_digits=10,
                        verbose_name="Dépôt minimum pour activation",
                    ),
                ),
                (
                    "bonus_on_signup",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Bonus octroyé au nouveau joueur qui utilise ce code",
                        max_digits=10,
                        verbose_name="Bonus à l'inscription",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("expired", "Expiré"),
                            ("suspended", "Suspendu"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Laissez vide pour pas de date d'expiration",
                        null=True,
                        verbose_name="Expire le",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Le code utilisé par défaut pour ce parrain",
                        verbose_name="Code principal",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="referrals.referralprogram",
                        verbose_name="Programme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code de parrainage",
                "verbose_name_plural": "Codes de parrainage",
                "db_table": "referral_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralCodeShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("direct", "Lien direct"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "shared_by_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP du partage"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Partagé le"),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="referrals.referralcode",
                        verbose_name="Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partage de code",
                "verbose_name_plural": "Partages de codes",
                "db_table": "referral_code_shares",
                "ordering": ["-shared_at"],
                "indexes": [
                    models.Index(
                        fields=["code", "shared_at"],
                        name="referral_co_code_id_bb54b2_idx",
                    ),
                    models.Index(
                        fields=["channel"], name="referral_co_channel_952557_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferralCodeClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Cliqué le"),
                ),
                (
                    "visitor_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP du visiteur"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "referrer",
                    models.CharField(
                        blank=True,
                        help_text="Où le clic venait",
                        max_length=500,
                        verbose_name="Provenance",
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Converti le"
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="referrals.referralcode",
                        verbose_name="Code",
                    ),
                ),
                (
                    "converted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_codes_converted_from",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur converti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clic sur code",
                "verbose_name_plural": "Clics sur codes",
                "db_table": "referral_code_clicks",
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["code", "clicked_at"],
                        name="referral_co_code_id_d575ec_idx",
                    ),
                    models.Index(
                        fields=["converted_user"], name="referral_co_convert_9aadbe_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(
                fields=["user", "status"], name="referral_co_user_id_638f5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(fields=["code"], name="referral_co_code_0cdd0e_idx"),
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(
                fields=["created_at"], name="referral_co_created_fbefb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(
                fields=["expires_at"], name="referral_co_expires_5e63bd_idx"
            ),
        ),
    ]
