# Generated by Django 4.2.7 on 2025-12-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0002_referralcode_referralcodeshare_referralcodeclick_and_more"),
        ("referrals", "0002_update_referral_system"),
    ]

    operations = []
