# Generated by Django 5.2.6 on 2025-09-25 06:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("player_id", models.CharField(db_index=True, max_length=100)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                ("level_reached", models.IntegerField(default=1)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Game Session",
                "verbose_name_plural": "Game Sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("total_sessions", models.IntegerField(default=0)),
                ("highest_score", models.IntegerField(default=0)),
                ("highest_level", models.IntegerField(default=0)),
                ("total_playtime", models.IntegerField(default=0)),
                (
                    "first_played",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_played",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Player Statistics",
                "verbose_name_plural": "Player Statistics",
            },
        ),
        migrations.CreateModel(
            name="GameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("level_start", "Level Start"),
                            ("level_complete", "Level Complete"),
                            ("game_over", "Game Over"),
                            ("power_up_used", "Power Up Used"),
                            ("achievement_unlocked", "Achievement Unlocked"),
                            ("item_collected", "Item Collected"),
                            ("obstacle_hit", "Obstacle Hit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.gamesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Event",
                "verbose_name_plural": "Game Events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
